### PR TITLE
Bump to ginkgo v2

### PR DESCRIPTION
**Pull request by moleske**
- didn't touch assets

leaving in draft til I run some tests making sure this still works

### CODE REVIEW

**Comment by moleske** [comment]
Didn't finish running the suite against a bosh-lite as I ran out of time but tests that did run were passing

Not sure if this will help stabilize our CI, but it would help get us to only use ginkgo 2 in CI.  Currently, this and sync integration tests use ginkgo 1, cf acceptance tests use ginkgo 2

**Comment by moleske** [comment]
Got around to running all the tests.  The only thing to note is that the default timeout in ginkgo 2 is 1 hour, so in our CI we'll likely want to override that timeout.  Otherwise all the tests seem to be working.  If no one has any thoughts/comments/questions/concerns about this, I'll merge it in toward the end of next week

**Comment by xandroc** [comment]
Thanks for doing the upgrade work and running the tests. Changes look good!

**Comment by moleske** [comment]
decided to get this up to date after not merging this in earlier.  currently running tests to make sure everything is still working.  will need to update the docker image to use ginkgo v2, but the bara tests currently use some [capi k8s file](https://github.com/cloudfoundry/capi-dockerfiles/blob/main/cf-for-k8s/Dockerfile) in the [pipeline.yml](https://github.com/cloudfoundry/capi-ci/blob/23cfe83060a0888f7d3c2167e9c80f29b7a426d1/ci/baras/run-baras.yml#L4-L8).  We probably want to get rid of the k8s docker image as it is super old base.  Maybe we can just use the [sits one](https://github.com/cloudfoundry/capi-dockerfiles/pull/37)

**Comment by moleske** [comment]
tests are passing, will need to [update some of the ginkgo flags](https://github.com/cloudfoundry/capi-ci/pull/45) used.  Specifically [timeout](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#timeout-behavior) as that has changed in v2

**Pull request merged**
